### ISSUE TITLE
Error opening the texte editor, tkhtml module failed to import.

### ISSUE THREAD

**Issue by N07070** [luke-carlson/advanced-text-editor#3]
Hello,
I tried to use your texte editor, and, it failed.
It outputed this error : 
`Traceback (most recent call last):
  File "/Users/Me/Downloads/advanced-text-editor-master/advanced_text_editor.py", line 8, in <module>
    from tkhtml import *
ImportError: No module named tkhtml`

How could i fix this ?

Thanks !

**Comment by Aareon** [comment]
@N07070 please do `py -3 -m pip install tkinterhtml` and report back whether or not it worked or still fails.

**Comment by N07070** [comment]
It works now. The proposed solution above worked. The issue came from a bad environment config.
