### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sam0hack** [luke-carlson/advanced-text-editor#4]
$~ python3 advanced_text_editor.py 

  File "advanced_text_editor.py", line 53
    print focus
              ^
SyntaxError: invalid syntax

**Comment by Aareon** [comment]
@sam0hack for this, simply search for `print ` in any text editor and replace with `print(` and append `)` to the end of the line

**Comment by rudrathegreat** [comment]
You have to do this if you have Python 3.X versions - 

```Python

print(focus)

```

You can to do this if you have Python 2.X versions - 

```Python

print focus

```
